const fs = require('fs');
const path = require('path');

const themes = [
  {
    name: 'Pure Vanilla Light',
    type: 'light',
    colors: {
      editorBackground: '#FFF8E7',
      editorForeground: '#4A3728',
      editorLineHighlight: '#FFF0D0',
      editorSelection: '#FFE4B5',
      editorCursor: '#D4AF37',
      editorLineNumbers: '#C4A97D',
      editorIndentGuides: '#E8D5B5',
      editorWhitespace: '#E0D0B0',
      editorBracketMatch: '#FFD700',
      editorWidgetBackground: '#FFF8E7',
      editorWidgetBorder: '#D4AF37',
      editorGutter: '#FFF8E7',
      editorError: '#FF6B35',
      editorWarning: '#9B59B6',
      editorInfo: '#2ECC71',
      editorFindMatch: '#FFD700',
      editorFindHighlight: '#FFF0C0',
      editorHoverHighlight: '#FFF0D0',
      editorLink: '#4A90D9',
      editorActiveLineNumber: '#D4AF37',
      editorRuler: '#E8D5B5',
      editorCodeLens: '#C4A97D',
      editorBracketPairColor1: '#D4AF37',
      editorBracketPairColor2: '#C0392B',
      editorBracketPairColor3: '#2980B9',
      titleBarBackground: '#FFF8E7',
      titleBarForeground: '#4A3728',
      titleBarBorder: '#E8D5B5',
      activityBarBackground: '#FFF0D0',
      activityBarForeground: '#4A3728',
      activityBarBorder: '#E8D5B5',
      activityBarBadgeBackground: '#D4AF37',
      activityBarBadgeForeground: '#FFFFFF',
      sideBarBackground: '#FFF8E7',
      sideBarForeground: '#4A3728',
      sideBarBorder: '#E8D5B5',
      sideBarTitleBackground: '#FFF0D0',
      sideBarSectionHeaderBackground: '#FFF0D0',
      listActiveBackground: '#FFE4B5',
      listActiveForeground: '#4A3728',
      listHoverBackground: '#FFF0D0',
      listHoverForeground: '#4A3728',
      listFocusBackground: '#FFE4B5',
      listHighlightForeground: '#D4AF37',
      inputBackground: '#FFFFFF',
      inputForeground: '#4A3728',
      inputBorder: '#E8D5B5',
      inputPlaceholderForeground: '#C4A97D',
      inputOptionActiveBackground: '#FFE4B5',
      inputOptionActiveBorder: '#D4AF37',
      inputValidationErrorBackground: '#FFE0D0',
      inputValidationErrorBorder: '#FF6B35',
      inputValidationWarningBackground: '#F0E0FF',
      inputValidationWarningBorder: '#9B59B6',
      inputValidationInfoBackground: '#E0FFE8',
      inputValidationInfoBorder: '#2ECC71',
      dropdownBackground: '#FFFFFF',
      dropdownForeground: '#4A3728',
      dropdownBorder: '#E8D5B5',
      buttonBackground: '#D4AF37',
      buttonForeground: '#FFFFFF',
      buttonHoverBackground: '#C4A030',
      buttonSecondaryBackground: '#E8D5B5',
      buttonSecondaryForeground: '#4A3728',
      buttonSecondaryHoverBackground: '#DCC8A0',
      badgeBackground: '#D4AF37',
      badgeForeground: '#FFFFFF',
      scrollbarShadow: '#E8D5B5',
      scrollbarSliderBackground: '#D4AF3780',
      scrollbarSliderHoverBackground: '#D4AF37B0',
      scrollbarSliderActiveBackground: '#D4AF37',
      panelBackground: '#FFF8E7',
      panelForeground: '#4A3728',
      panelBorder: '#E8D5B5',
      panelTitleActiveForeground: '#D4AF37',
      panelTitleInactiveForeground: '#C4A97D',
      panelInputBackground: '#FFFFFF',
      statusBarBackground: '#D4AF37',
      statusBarForeground: '#FFFFFF',
      statusBarBorder: '#C4A030',
      statusBarDebuggingBackground: '#FF6B35',
      statusBarDebuggingForeground: '#FFFFFF',
      statusBarNoFolderBackground: '#E8D5B5',
      statusBarItemHoverBackground: '#C4A030',
      statusBarItemProminentBackground: '#C4A030',
      statusBarItemProminentHoverBackground: '#B49020',
      tabActiveBackground: '#FFF8E7',
      tabActiveForeground: '#D4AF37',
      tabActiveBorder: '#D4AF37',
      tabInactiveBackground: '#FFF0D0',
      tabInactiveForeground: '#8A7A6A',
      tabHoverBackground: '#FFE4B5',
      tabBorder: '#E8D5B5',
      terminalBackground: '#1E1E1E',
      terminalForeground: '#D4D4D4',
      terminalCursor: '#D4AF37',
      terminalCursorBackground: '#FFFFFF',
      terminalAnsiBlack: '#000000',
      terminalAnsiRed: '#FF6B35',
      terminalAnsiGreen: '#2ECC71',
      terminalAnsiYellow: '#D4AF37',
      terminalAnsiBlue: '#4A90D9',
      terminalAnsiMagenta: '#9B59B6',
      terminalAnsiCyan: '#1ABC9C',
      terminalAnsiWhite: '#FFFFFF',
      terminalAnsiBrightBlack: '#666666',
      terminalAnsiBrightRed: '#FF8C5A',
      terminalAnsiBrightGreen: '#58D68D',
      terminalAnsiBrightYellow: '#F4D03F',
      terminalAnsiBrightBlue: '#6DB3E6',
      terminalAnsiBrightMagenta: '#B87ED4',
      terminalAnsiBrightCyan: '#48C9B0',
      terminalAnsiBrightWhite: '#FFFFFF',
      debugToolBarBackground: '#FFF0D0',
      debugExceptionWidgetBackground: '#FFE0D0',
      debugExceptionWidgetBorder: '#FF6B35',
      minimapBackground: '#FFF8E7',
      minimapFindMatchHighlight: '#FFD700',
      minimapSelectionHighlight: '#FFE4B5',
      minimapErrorHighlight: '#FF6B35',
      minimapWarningHighlight: '#9B59B6',
      breadcrumbBackground: '#FFF8E7',
      breadcrumbForeground: '#8A7A6A',
      breadcrumbFocusForeground: '#4A3728',
      breadcrumbActiveSelectionForeground: '#D4AF37',
      mergeCurrentHeaderBackground: '#2ECC7180',
      mergeCurrentContentBackground: '#2ECC7130',
      mergeIncomingHeaderBackground: '#4A90D980',
      mergeIncomingContentBackground: '#4A90D930',
      mergeCommonHeaderBackground: '#8A7A6A80',
      mergeCommonContentBackground: '#8A7A6A30',
      settingsHeaderForeground: '#D4AF37',
      settingsModifiedItemIndicator: '#D4AF37',
      settingsDropdownBackground: '#FFFFFF',
      settingsDropdownForeground: '#4A3728',
      settingsDropdownBorder: '#E8D5B5',
      settingsCheckboxBackground: '#FFFFFF',
      settingsCheckboxForeground: '#4A3728',
      settingsCheckboxBorder: '#E8D5B5',
      settingsTextInputBackground: '#FFFFFF',
      settingsTextInputForeground: '#4A3728',
      settingsTextInputBorder: '#E8D5B5',
      settingsNumberInputBackground: '#FFFFFF',
      settingsNumberInputForeground: '#4A3728',
      settingsNumberInputBorder: '#E8D5B5',
      focusBorder: '#D4AF37',
      foreground: '#4A3728',
      widgetShadow: '#00000020',
      selectionBackground: '#FFE4B5',
      errorForeground: '#FF6B35',
      descriptionForeground: '#8A7A6A',
      iconForeground: '#D4AF37',
      progressBarBackground: '#D4AF37',
    },
    tokenColors: [
      // Royal Gold - Keywords
      { scope: ['keyword.control.bloom.purelily', 'keyword.control.ancient.purelily', 'keyword.control.wish.purelily', 'keyword.control.friend.purelily', 'keyword.control.heal.purelily', 'keyword.control.iflight.purelily', 'keyword.control.moonpath.purelily', 'keyword.control.repeat.purelily', 'keyword.control.timeflow.purelily', 'keyword.control.purelily', 'keyword.other.purelily'], settings: { foreground: '#D4AF37', fontStyle: 'bold' } },
      // Timekeeper Purple - Async keywords
      { scope: ['keyword.async.purelily'], settings: { foreground: '#8B5CF6', fontStyle: 'bold' } },
      // White Lily Green - Strings
      { scope: ['string.quoted.double.purelily'], settings: { foreground: '#2ECC71' } },
      // Golden Cheese Yellow - Numbers
      { scope: ['constant.numeric.purelily'], settings: { foreground: '#F1C40F' } },
      // Pure Vanilla Cream - Functions
      { scope: ['entity.name.function.purelily'], settings: { foreground: '#F5DEB3' } },
      // Hollyberry Crimson - Types/Classes
      { scope: ['entity.name.type.purelily'], settings: { foreground: '#C0392B', fontStyle: 'bold' } },
      // Moonlight Blue - Modules
      { scope: ['support.module.purelily'], settings: { foreground: '#4A90D9' } },
      // Frost Queen Cyan - Comments
      { scope: ['comment.line.double-slash.purelily', 'comment.block.purelily'], settings: { foreground: '#1ABC9C', fontStyle: 'italic' } },
      // Ancient Gold - Constants
      { scope: ['constant.other.purelily'], settings: { foreground: '#B8860B', fontStyle: 'bold' } },
      // Burning Spice Orange - Errors
      { scope: ['markup.deleted', 'invalid'], settings: { foreground: '#FF6B35', fontStyle: 'bold' } },
      // Mystic Flour Violet - Warnings
      { scope: ['markup.changed', 'warning'], settings: { foreground: '#9B59B6' } },
      // Emerald Green - Success
      { scope: ['markup.inserted'], settings: { foreground: '#2ECC71', fontStyle: 'bold' } },
      // Operators
      { scope: ['keyword.operator.purelily'], settings: { foreground: '#D4AF37' } },
    ]
  },
  {
    name: 'White Lily Garden',
    type: 'light',
    colors: {
      editorBackground: '#F0FFF4',
      editorForeground: '#2D3A2D',
      editorLineHighlight: '#E0FFE8',
      editorSelection: '#C8F0D0',
      editorCursor: '#2ECC71',
      editorLineNumbers: '#8AB89A',
      editorIndentGuides: '#D0E8D0',
      activityBarBackground: '#E0FFE8',
      activityBarForeground: '#2D3A2D',
      sideBarBackground: '#F0FFF4',
      sideBarBorder: '#D0E8D0',
      listActiveBackground: '#C8F0D0',
      statusBarBackground: '#2ECC71',
      statusBarForeground: '#FFFFFF',
      tabActiveBorder: '#2ECC71',
      inputBorder: '#D0E8D0',
      buttonBackground: '#2ECC71',
      focusBorder: '#2ECC71',
      titleBarBackground: '#F0FFF4',
      titleBarForeground: '#2D3A2D',
      panelBorder: '#D0E8D0',
      dropdownBorder: '#D0E8D0',
      scrollbarSliderBackground: '#2ECC7180',
    },
    tokenColors: [
      { scope: ['keyword.control.bloom.purelily', 'keyword.control.ancient.purelily', 'keyword.control.wish.purelily', 'keyword.control.friend.purelily', 'keyword.control.heal.purelily', 'keyword.control.iflight.purelily', 'keyword.control.moonpath.purelily', 'keyword.control.repeat.purelily', 'keyword.control.timeflow.purelily', 'keyword.control.purelily', 'keyword.other.purelily'], settings: { foreground: '#27AE60', fontStyle: 'bold' } },
      { scope: ['keyword.async.purelily'], settings: { foreground: '#8B5CF6', fontStyle: 'bold' } },
      { scope: ['string.quoted.double.purelily'], settings: { foreground: '#1ABC9C' } },
      { scope: ['constant.numeric.purelily'], settings: { foreground: '#F39C12' } },
      { scope: ['entity.name.function.purelily'], settings: { foreground: '#F5DEB3' } },
      { scope: ['entity.name.type.purelily'], settings: { foreground: '#C0392B', fontStyle: 'bold' } },
      { scope: ['support.module.purelily'], settings: { foreground: '#2980B9' } },
      { scope: ['comment.line.double-slash.purelily', 'comment.block.purelily'], settings: { foreground: '#2ECC71', fontStyle: 'italic' } },
      { scope: ['constant.other.purelily'], settings: { foreground: '#B8860B', fontStyle: 'bold' } },
    ]
  },
  {
    name: 'Hollyberry Kingdom',
    type: 'dark',
    colors: {
      editorBackground: '#1A0A0A',
      editorForeground: '#F0D0D0',
      editorLineHighlight: '#2A1515',
      editorSelection: '#4A2020',
      editorCursor: '#E74C3C',
      editorLineNumbers: '#8A4040',
      editorIndentGuides: '#3A2020',
      activityBarBackground: '#2A1515',
      activityBarForeground: '#E74C3C',
      sideBarBackground: '#1A0A0A',
      sideBarBorder: '#3A2020',
      listActiveBackground: '#4A2020',
      statusBarBackground: '#C0392B',
      statusBarForeground: '#FFFFFF',
      tabActiveBorder: '#E74C3C',
      inputBackground: '#2A1515',
      inputForeground: '#F0D0D0',
      inputBorder: '#4A2020',
      buttonBackground: '#C0392B',
      focusBorder: '#E74C3C',
      titleBarBackground: '#1A0A0A',
      titleBarForeground: '#E74C3C',
      terminalBackground: '#1A0A0A',
      terminalForeground: '#F0D0D0',
      terminalCursor: '#E74C3C',
      terminalAnsiRed: '#E74C3C',
      terminalAnsiGreen: '#2ECC71',
      terminalAnsiYellow: '#F1C40F',
      terminalAnsiBlue: '#3498DB',
      terminalAnsiMagenta: '#9B59B6',
      terminalAnsiCyan: '#1ABC9C',
      panelBackground: '#1A0A0A',
      panelBorder: '#3A2020',
      dropdownBackground: '#2A1515',
      dropdownForeground: '#F0D0D0',
      dropdownBorder: '#4A2020',
      scrollbarSliderBackground: '#C0392B80',
    },
    tokenColors: [
      { scope: ['keyword.control.bloom.purelily', 'keyword.control.ancient.purelily', 'keyword.control.wish.purelily', 'keyword.control.friend.purelily', 'keyword.control.heal.purelily', 'keyword.control.iflight.purelily', 'keyword.control.moonpath.purelily', 'keyword.control.repeat.purelily', 'keyword.control.timeflow.purelily', 'keyword.control.purelily', 'keyword.other.purelily'], settings: { foreground: '#E74C3C', fontStyle: 'bold' } },
      { scope: ['keyword.async.purelily'], settings: { foreground: '#9B59B6', fontStyle: 'bold' } },
      { scope: ['string.quoted.double.purelily'], settings: { foreground: '#2ECC71' } },
      { scope: ['constant.numeric.purelily'], settings: { foreground: '#F1C40F' } },
      { scope: ['entity.name.function.purelily'], settings: { foreground: '#F5DEB3' } },
      { scope: ['entity.name.type.purelily'], settings: { foreground: '#E74C3C', fontStyle: 'bold' } },
      { scope: ['support.module.purelily'], settings: { foreground: '#3498DB' } },
      { scope: ['comment.line.double-slash.purelily', 'comment.block.purelily'], settings: { foreground: '#1ABC9C', fontStyle: 'italic' } },
      { scope: ['constant.other.purelily'], settings: { foreground: '#F1C40F', fontStyle: 'bold' } },
    ]
  },
  {
    name: 'Dark Cacao Night',
    type: 'dark',
    colors: {
      editorBackground: '#0D0D1A',
      editorForeground: '#C0C0D0',
      editorLineHighlight: '#1A1A2E',
      editorSelection: '#2D2D4A',
      editorCursor: '#6C63FF',
      editorLineNumbers: '#4A4A6A',
      editorIndentGuides: '#2A2A40',
      activityBarBackground: '#1A1A2E',
      activityBarForeground: '#6C63FF',
      sideBarBackground: '#0D0D1A',
      sideBarBorder: '#2A2A40',
      listActiveBackground: '#2D2D4A',
      statusBarBackground: '#6C63FF',
      statusBarForeground: '#FFFFFF',
      tabActiveBorder: '#6C63FF',
      inputBackground: '#1A1A2E',
      inputForeground: '#C0C0D0',
      inputBorder: '#2D2D4A',
      buttonBackground: '#6C63FF',
      focusBorder: '#6C63FF',
      titleBarBackground: '#0D0D1A',
      titleBarForeground: '#6C63FF',
      terminalBackground: '#0D0D1A',
      terminalForeground: '#C0C0D0',
      terminalCursor: '#6C63FF',
      terminalAnsiBlue: '#6C63FF',
      terminalAnsiMagenta: '#9B59B6',
      panelBackground: '#0D0D1A',
      panelBorder: '#2A2A40',
      dropdownBackground: '#1A1A2E',
      dropdownForeground: '#C0C0D0',
      dropdownBorder: '#2D2D4A',
      scrollbarSliderBackground: '#6C63FF80',
    },
    tokenColors: [
      { scope: ['keyword.control.bloom.purelily', 'keyword.control.ancient.purelily', 'keyword.control.wish.purelily', 'keyword.control.friend.purelily', 'keyword.control.heal.purelily', 'keyword.control.iflight.purelily', 'keyword.control.moonpath.purelily', 'keyword.control.repeat.purelily', 'keyword.control.timeflow.purelily', 'keyword.control.purelily', 'keyword.other.purelily'], settings: { foreground: '#6C63FF', fontStyle: 'bold' } },
      { scope: ['keyword.async.purelily'], settings: { foreground: '#8B5CF6', fontStyle: 'bold' } },
      { scope: ['string.quoted.double.purelily'], settings: { foreground: '#2ECC71' } },
      { scope: ['constant.numeric.purelily'], settings: { foreground: '#F1C40F' } },
      { scope: ['entity.name.function.purelily'], settings: { foreground: '#F5DEB3' } },
      { scope: ['entity.name.type.purelily'], settings: { foreground: '#E74C3C', fontStyle: 'bold' } },
      { scope: ['support.module.purelily'], settings: { foreground: '#3498DB' } },
      { scope: ['comment.line.double-slash.purelily', 'comment.block.purelily'], settings: { foreground: '#1ABC9C', fontStyle: 'italic' } },
      { scope: ['constant.other.purelily'], settings: { foreground: '#F1C40F', fontStyle: 'bold' } },
    ]
  },
  {
    name: 'Golden Cheese Treasury',
    type: 'light',
    colors: {
      editorBackground: '#FFFDF0',
      editorForeground: '#4A3F20',
      editorLineHighlight: '#FFF8D0',
      editorSelection: '#FFE4A0',
      editorCursor: '#D4A017',
      editorLineNumbers: '#C4A040',
      editorIndentGuides: '#E8D8A0',
      activityBarBackground: '#FFE4A0',
      activityBarForeground: '#4A3F20',
      sideBarBackground: '#FFFDF0',
      sideBarBorder: '#E8D8A0',
      listActiveBackground: '#FFE4A0',
      statusBarBackground: '#D4A017',
      statusBarForeground: '#FFFFFF',
      tabActiveBorder: '#D4A017',
      inputBorder: '#E8D8A0',
      buttonBackground: '#D4A017',
      focusBorder: '#D4A017',
      titleBarBackground: '#FFFDF0',
      titleBarForeground: '#D4A017',
      panelBorder: '#E8D8A0',
      dropdownBorder: '#E8D8A0',
      scrollbarSliderBackground: '#D4A01780',
    },
    tokenColors: [
      { scope: ['keyword.control.bloom.purelily', 'keyword.control.ancient.purelily', 'keyword.control.wish.purelily', 'keyword.control.friend.purelily', 'keyword.control.heal.purelily', 'keyword.control.iflight.purelily', 'keyword.control.moonpath.purelily', 'keyword.control.repeat.purelily', 'keyword.control.timeflow.purelily', 'keyword.control.purelily', 'keyword.other.purelily'], settings: { foreground: '#B8860B', fontStyle: 'bold' } },
      { scope: ['keyword.async.purelily'], settings: { foreground: '#8B5CF6', fontStyle: 'bold' } },
      { scope: ['string.quoted.double.purelily'], settings: { foreground: '#2ECC71' } },
      { scope: ['constant.numeric.purelily'], settings: { foreground: '#D4A017' } },
      { scope: ['entity.name.function.purelily'], settings: { foreground: '#CD853F' } },
      { scope: ['entity.name.type.purelily'], settings: { foreground: '#C0392B', fontStyle: 'bold' } },
      { scope: ['support.module.purelily'], settings: { foreground: '#4A90D9' } },
      { scope: ['comment.line.double-slash.purelily', 'comment.block.purelily'], settings: { foreground: '#1ABC9C', fontStyle: 'italic' } },
      { scope: ['constant.other.purelily'], settings: { foreground: '#B8860B', fontStyle: 'bold' } },
    ]
  },
  {
    name: 'Moonlight Dreamscape',
    type: 'dark',
    colors: {
      editorBackground: '#0A0A2E',
      editorForeground: '#C0C0F0',
      editorLineHighlight: '#151540',
      editorSelection: '#252560',
      editorCursor: '#7C7CFF',
      editorLineNumbers: '#404080',
      editorIndentGuides: '#202050',
      activityBarBackground: '#151540',
      activityBarForeground: '#7C7CFF',
      sideBarBackground: '#0A0A2E',
      sideBarBorder: '#202050',
      listActiveBackground: '#252560',
      statusBarBackground: '#4A4AD0',
      statusBarForeground: '#FFFFFF',
      tabActiveBorder: '#7C7CFF',
      inputBackground: '#151540',
      inputForeground: '#C0C0F0',
      inputBorder: '#252560',
      buttonBackground: '#4A4AD0',
      focusBorder: '#7C7CFF',
      titleBarBackground: '#0A0A2E',
      titleBarForeground: '#7C7CFF',
      terminalBackground: '#0A0A2E',
      terminalForeground: '#C0C0F0',
      terminalCursor: '#7C7CFF',
      terminalAnsiBlue: '#7C7CFF',
      terminalAnsiMagenta: '#9B59B6',
      panelBackground: '#0A0A2E',
      panelBorder: '#202050',
      dropdownBackground: '#151540',
      dropdownForeground: '#C0C0F0',
      dropdownBorder: '#252560',
      scrollbarSliderBackground: '#7C7CFF80',
    },
    tokenColors: [
      { scope: ['keyword.control.bloom.purelily', 'keyword.control.ancient.purelily', 'keyword.control.wish.purelily', 'keyword.control.friend.purelily', 'keyword.control.heal.purelily', 'keyword.control.iflight.purelily', 'keyword.control.moonpath.purelily', 'keyword.control.repeat.purelily', 'keyword.control.timeflow.purelily', 'keyword.control.purelily', 'keyword.other.purelily'], settings: { foreground: '#7C7CFF', fontStyle: 'bold' } },
      { scope: ['keyword.async.purelily'], settings: { foreground: '#9B59B6', fontStyle: 'bold' } },
      { scope: ['string.quoted.double.purelily'], settings: { foreground: '#2ECC71' } },
      { scope: ['constant.numeric.purelily'], settings: { foreground: '#F1C40F' } },
      { scope: ['entity.name.function.purelily'], settings: { foreground: '#F5DEB3' } },
      { scope: ['entity.name.type.purelily'], settings: { foreground: '#E74C3C', fontStyle: 'bold' } },
      { scope: ['support.module.purelily'], settings: { foreground: '#7C7CFF' } },
      { scope: ['comment.line.double-slash.purelily', 'comment.block.purelily'], settings: { foreground: '#1ABC9C', fontStyle: 'italic' } },
      { scope: ['constant.other.purelily'], settings: { foreground: '#F1C40F', fontStyle: 'bold' } },
    ]
  },
  {
    name: 'Sea Fairy Ocean',
    type: 'dark',
    colors: {
      editorBackground: '#001520',
      editorForeground: '#B0D0E0',
      editorLineHighlight: '#002A40',
      editorSelection: '#004060',
      editorCursor: '#00BFFF',
      editorLineNumbers: '#006080',
      editorIndentGuides: '#003050',
      activityBarBackground: '#002A40',
      activityBarForeground: '#00BFFF',
      sideBarBackground: '#001520',
      sideBarBorder: '#003050',
      listActiveBackground: '#004060',
      statusBarBackground: '#0080C0',
      statusBarForeground: '#FFFFFF',
      tabActiveBorder: '#00BFFF',
      inputBackground: '#002A40',
      inputForeground: '#B0D0E0',
      inputBorder: '#004060',
      buttonBackground: '#0080C0',
      focusBorder: '#00BFFF',
      titleBarBackground: '#001520',
      titleBarForeground: '#00BFFF',
      terminalBackground: '#001520',
      terminalForeground: '#B0D0E0',
      terminalCursor: '#00BFFF',
      terminalAnsiCyan: '#00BFFF',
      terminalAnsiBlue: '#0080C0',
      panelBackground: '#001520',
      panelBorder: '#003050',
      dropdownBackground: '#002A40',
      dropdownForeground: '#B0D0E0',
      dropdownBorder: '#004060',
      scrollbarSliderBackground: '#00BFFF80',
    },
    tokenColors: [
      { scope: ['keyword.control.bloom.purelily', 'keyword.control.ancient.purelily', 'keyword.control.wish.purelily', 'keyword.control.friend.purelily', 'keyword.control.heal.purelily', 'keyword.control.iflight.purelily', 'keyword.control.moonpath.purelily', 'keyword.control.repeat.purelily', 'keyword.control.timeflow.purelily', 'keyword.control.purelily', 'keyword.other.purelily'], settings: { foreground: '#00BFFF', fontStyle: 'bold' } },
      { scope: ['keyword.async.purelily'], settings: { foreground: '#9B59B6', fontStyle: 'bold' } },
      { scope: ['string.quoted.double.purelily'], settings: { foreground: '#2ECC71' } },
      { scope: ['constant.numeric.purelily'], settings: { foreground: '#F1C40F' } },
      { scope: ['entity.name.function.purelily'], settings: { foreground: '#F5DEB3' } },
      { scope: ['entity.name.type.purelily'], settings: { foreground: '#E74C3C', fontStyle: 'bold' } },
      { scope: ['support.module.purelily'], settings: { foreground: '#00BFFF' } },
      { scope: ['comment.line.double-slash.purelily', 'comment.block.purelily'], settings: { foreground: '#1ABC9C', fontStyle: 'italic' } },
      { scope: ['constant.other.purelily'], settings: { foreground: '#F1C40F', fontStyle: 'bold' } },
    ]
  },
  {
    name: 'Frost Queen Winter',
    type: 'dark',
    colors: {
      editorBackground: '#0A1520',
      editorForeground: '#C0D8E8',
      editorLineHighlight: '#152838',
      editorSelection: '#204050',
      editorCursor: '#1ABC9C',
      editorLineNumbers: '#306070',
      editorIndentGuides: '#1A3040',
      activityBarBackground: '#152838',
      activityBarForeground: '#1ABC9C',
      sideBarBackground: '#0A1520',
      sideBarBorder: '#1A3040',
      listActiveBackground: '#204050',
      statusBarBackground: '#1ABC9C',
      statusBarForeground: '#FFFFFF',
      tabActiveBorder: '#1ABC9C',
      inputBackground: '#152838',
      inputForeground: '#C0D8E8',
      inputBorder: '#204050',
      buttonBackground: '#1ABC9C',
      focusBorder: '#1ABC9C',
      titleBarBackground: '#0A1520',
      titleBarForeground: '#1ABC9C',
      terminalBackground: '#0A1520',
      terminalForeground: '#C0D8E8',
      terminalCursor: '#1ABC9C',
      terminalAnsiCyan: '#1ABC9C',
      panelBackground: '#0A1520',
      panelBorder: '#1A3040',
      dropdownBackground: '#152838',
      dropdownForeground: '#C0D8E8',
      dropdownBorder: '#204050',
      scrollbarSliderBackground: '#1ABC9C80',
    },
    tokenColors: [
      { scope: ['keyword.control.bloom.purelily', 'keyword.control.ancient.purelily', 'keyword.control.wish.purelily', 'keyword.control.friend.purelily', 'keyword.control.heal.purelily', 'keyword.control.iflight.purelily', 'keyword.control.moonpath.purelily', 'keyword.control.repeat.purelily', 'keyword.control.timeflow.purelily', 'keyword.control.purelily', 'keyword.other.purelily'], settings: { foreground: '#1ABC9C', fontStyle: 'bold' } },
      { scope: ['keyword.async.purelily'], settings: { foreground: '#9B59B6', fontStyle: 'bold' } },
      { scope: ['string.quoted.double.purelily'], settings: { foreground: '#2ECC71' } },
      { scope: ['constant.numeric.purelily'], settings: { foreground: '#F1C40F' } },
      { scope: ['entity.name.function.purelily'], settings: { foreground: '#F5DEB3' } },
      { scope: ['entity.name.type.purelily'], settings: { foreground: '#E74C3C', fontStyle: 'bold' } },
      { scope: ['support.module.purelily'], settings: { foreground: '#3498DB' } },
      { scope: ['comment.line.double-slash.purelily', 'comment.block.purelily'], settings: { foreground: '#1ABC9C', fontStyle: 'italic' } },
      { scope: ['constant.other.purelily'], settings: { foreground: '#F1C40F', fontStyle: 'bold' } },
    ]
  },
  {
    name: 'Black Pearl Abyss',
    type: 'dark',
    colors: {
      editorBackground: '#0A000A',
      editorForeground: '#D0B8D8',
      editorLineHighlight: '#1A1020',
      editorSelection: '#2D1840',
      editorCursor: '#9B59B6',
      editorLineNumbers: '#4A2A60',
      editorIndentGuides: '#201530',
      activityBarBackground: '#1A1020',
      activityBarForeground: '#9B59B6',
      sideBarBackground: '#0A000A',
      sideBarBorder: '#201530',
      listActiveBackground: '#2D1840',
      statusBarBackground: '#7D3C98',
      statusBarForeground: '#FFFFFF',
      tabActiveBorder: '#9B59B6',
      inputBackground: '#1A1020',
      inputForeground: '#D0B8D8',
      inputBorder: '#2D1840',
      buttonBackground: '#7D3C98',
      focusBorder: '#9B59B6',
      titleBarBackground: '#0A000A',
      titleBarForeground: '#9B59B6',
      terminalBackground: '#0A000A',
      terminalForeground: '#D0B8D8',
      terminalCursor: '#9B59B6',
      terminalAnsiMagenta: '#9B59B6',
      terminalAnsiCyan: '#1ABC9C',
      panelBackground: '#0A000A',
      panelBorder: '#201530',
      dropdownBackground: '#1A1020',
      dropdownForeground: '#D0B8D8',
      dropdownBorder: '#2D1840',
      scrollbarSliderBackground: '#9B59B680',
    },
    tokenColors: [
      { scope: ['keyword.control.bloom.purelily', 'keyword.control.ancient.purelily', 'keyword.control.wish.purelily', 'keyword.control.friend.purelily', 'keyword.control.heal.purelily', 'keyword.control.iflight.purelily', 'keyword.control.moonpath.purelily', 'keyword.control.repeat.purelily', 'keyword.control.timeflow.purelily', 'keyword.control.purelily', 'keyword.other.purelily'], settings: { foreground: '#9B59B6', fontStyle: 'bold' } },
      { scope: ['keyword.async.purelily'], settings: { foreground: '#8B5CF6', fontStyle: 'bold' } },
      { scope: ['string.quoted.double.purelily'], settings: { foreground: '#2ECC71' } },
      { scope: ['constant.numeric.purelily'], settings: { foreground: '#F1C40F' } },
      { scope: ['entity.name.function.purelily'], settings: { foreground: '#F5DEB3' } },
      { scope: ['entity.name.type.purelily'], settings: { foreground: '#E74C3C', fontStyle: 'bold' } },
      { scope: ['support.module.purelily'], settings: { foreground: '#3498DB' } },
      { scope: ['comment.line.double-slash.purelily', 'comment.block.purelily'], settings: { foreground: '#1ABC9C', fontStyle: 'italic' } },
      { scope: ['constant.other.purelily'], settings: { foreground: '#F1C40F', fontStyle: 'bold' } },
    ]
  },
  {
    name: 'Wind Archer Forest',
    type: 'dark',
    colors: {
      editorBackground: '#0A1A0A',
      editorForeground: '#C0E0C0',
      editorLineHighlight: '#152815',
      editorSelection: '#204020',
      editorCursor: '#2ECC71',
      editorLineNumbers: '#306030',
      editorIndentGuides: '#1A301A',
      activityBarBackground: '#152815',
      activityBarForeground: '#2ECC71',
      sideBarBackground: '#0A1A0A',
      sideBarBorder: '#1A301A',
      listActiveBackground: '#204020',
      statusBarBackground: '#27AE60',
      statusBarForeground: '#FFFFFF',
      tabActiveBorder: '#2ECC71',
      inputBackground: '#152815',
      inputForeground: '#C0E0C0',
      inputBorder: '#204020',
      buttonBackground: '#27AE60',
      focusBorder: '#2ECC71',
      titleBarBackground: '#0A1A0A',
      titleBarForeground: '#2ECC71',
      terminalBackground: '#0A1A0A',
      terminalForeground: '#C0E0C0',
      terminalCursor: '#2ECC71',
      terminalAnsiGreen: '#2ECC71',
      panelBackground: '#0A1A0A',
      panelBorder: '#1A301A',
      dropdownBackground: '#152815',
      dropdownForeground: '#C0E0C0',
      dropdownBorder: '#204020',
      scrollbarSliderBackground: '#2ECC7180',
    },
    tokenColors: [
      { scope: ['keyword.control.bloom.purelily', 'keyword.control.ancient.purelily', 'keyword.control.wish.purelily', 'keyword.control.friend.purelily', 'keyword.control.heal.purelily', 'keyword.control.iflight.purelily', 'keyword.control.moonpath.purelily', 'keyword.control.repeat.purelily', 'keyword.control.timeflow.purelily', 'keyword.control.purelily', 'keyword.other.purelily'], settings: { foreground: '#2ECC71', fontStyle: 'bold' } },
      { scope: ['keyword.async.purelily'], settings: { foreground: '#9B59B6', fontStyle: 'bold' } },
      { scope: ['string.quoted.double.purelily'], settings: { foreground: '#1ABC9C' } },
      { scope: ['constant.numeric.purelily'], settings: { foreground: '#F1C40F' } },
      { scope: ['entity.name.function.purelily'], settings: { foreground: '#F5DEB3' } },
      { scope: ['entity.name.type.purelily'], settings: { foreground: '#E74C3C', fontStyle: 'bold' } },
      { scope: ['support.module.purelily'], settings: { foreground: '#3498DB' } },
      { scope: ['comment.line.double-slash.purelily', 'comment.block.purelily'], settings: { foreground: '#1ABC9C', fontStyle: 'italic' } },
      { scope: ['constant.other.purelily'], settings: { foreground: '#F1C40F', fontStyle: 'bold' } },
    ]
  },
  {
    name: 'Timekeeper Timeline',
    type: 'dark',
    colors: {
      editorBackground: '#0A001A',
      editorForeground: '#C0B0E0',
      editorLineHighlight: '#1A0030',
      editorSelection: '#2D0050',
      editorCursor: '#8B5CF6',
      editorLineNumbers: '#4A0070',
      editorIndentGuides: '#200040',
      activityBarBackground: '#1A0030',
      activityBarForeground: '#8B5CF6',
      sideBarBackground: '#0A001A',
      sideBarBorder: '#200040',
      listActiveBackground: '#2D0050',
      statusBarBackground: '#7C3AED',
      statusBarForeground: '#FFFFFF',
      tabActiveBorder: '#8B5CF6',
      inputBackground: '#1A0030',
      inputForeground: '#C0B0E0',
      inputBorder: '#2D0050',
      buttonBackground: '#7C3AED',
      focusBorder: '#8B5CF6',
      titleBarBackground: '#0A001A',
      titleBarForeground: '#8B5CF6',
      terminalBackground: '#0A001A',
      terminalForeground: '#C0B0E0',
      terminalCursor: '#8B5CF6',
      terminalAnsiMagenta: '#8B5CF6',
      terminalAnsiCyan: '#1ABC9C',
      panelBackground: '#0A001A',
      panelBorder: '#200040',
      dropdownBackground: '#1A0030',
      dropdownForeground: '#C0B0E0',
      dropdownBorder: '#2D0050',
      scrollbarSliderBackground: '#8B5CF680',
    },
    tokenColors: [
      { scope: ['keyword.control.bloom.purelily', 'keyword.control.ancient.purelily', 'keyword.control.wish.purelily', 'keyword.control.friend.purelily', 'keyword.control.heal.purelily', 'keyword.control.iflight.purelily', 'keyword.control.moonpath.purelily', 'keyword.control.repeat.purelily', 'keyword.control.timeflow.purelily', 'keyword.control.purelily', 'keyword.other.purelily'], settings: { foreground: '#8B5CF6', fontStyle: 'bold' } },
      { scope: ['keyword.async.purelily'], settings: { foreground: '#A78BFA', fontStyle: 'bold' } },
      { scope: ['string.quoted.double.purelily'], settings: { foreground: '#2ECC71' } },
      { scope: ['constant.numeric.purelily'], settings: { foreground: '#F1C40F' } },
      { scope: ['entity.name.function.purelily'], settings: { foreground: '#F5DEB3' } },
      { scope: ['entity.name.type.purelily'], settings: { foreground: '#E74C3C', fontStyle: 'bold' } },
      { scope: ['support.module.purelily'], settings: { foreground: '#3498DB' } },
      { scope: ['comment.line.double-slash.purelily', 'comment.block.purelily'], settings: { foreground: '#1ABC9C', fontStyle: 'italic' } },
      { scope: ['constant.other.purelily'], settings: { foreground: '#F1C40F', fontStyle: 'bold' } },
    ]
  },
  {
    name: 'Anniversary Celebration',
    type: 'light',
    colors: {
      editorBackground: '#FFF0E0',
      editorForeground: '#4A2A1A',
      editorLineHighlight: '#FFE0C0',
      editorSelection: '#FFD0A0',
      editorCursor: '#FF6B35',
      editorLineNumbers: '#C08060',
      editorIndentGuides: '#E8C8A0',
      activityBarBackground: '#FF6347',
      activityBarForeground: '#FFFFFF',
      sideBarBackground: '#FFF0E0',
      sideBarBorder: '#E8C8A0',
      listActiveBackground: '#FFD0A0',
      statusBarBackground: '#FF6B35',
      statusBarForeground: '#FFFFFF',
      tabActiveBorder: '#FF6B35',
      inputBorder: '#E8C8A0',
      buttonBackground: '#FF6B35',
      focusBorder: '#FFD700',
      titleBarBackground: '#FF6B35',
      titleBarForeground: '#FFFFFF',
      panelBorder: '#E8C8A0',
      dropdownBorder: '#E8C8A0',
      scrollbarSliderBackground: '#FF6B3580',
    },
    tokenColors: [
      { scope: ['keyword.control.bloom.purelily', 'keyword.control.ancient.purelily', 'keyword.control.wish.purelily', 'keyword.control.friend.purelily', 'keyword.control.heal.purelily', 'keyword.control.iflight.purelily', 'keyword.control.moonpath.purelily', 'keyword.control.repeat.purelily', 'keyword.control.timeflow.purelily', 'keyword.control.purelily', 'keyword.other.purelily'], settings: { foreground: '#FF6B35', fontStyle: 'bold' } },
      { scope: ['keyword.async.purelily'], settings: { foreground: '#8B5CF6', fontStyle: 'bold' } },
      { scope: ['string.quoted.double.purelily'], settings: { foreground: '#2ECC71' } },
      { scope: ['constant.numeric.purelily'], settings: { foreground: '#F1C40F' } },
      { scope: ['entity.name.function.purelily'], settings: { foreground: '#F5DEB3' } },
      { scope: ['entity.name.type.purelily'], settings: { foreground: '#C0392B', fontStyle: 'bold' } },
      { scope: ['support.module.purelily'], settings: { foreground: '#4A90D9' } },
      { scope: ['comment.line.double-slash.purelily', 'comment.block.purelily'], settings: { foreground: '#1ABC9C', fontStyle: 'italic' } },
      { scope: ['constant.other.purelily'], settings: { foreground: '#FFD700', fontStyle: 'bold' } },
      { scope: ['markup.deleted', 'invalid'], settings: { foreground: '#FF6B35', fontStyle: 'bold' } },
      { scope: ['markup.changed', 'warning'], settings: { foreground: '#9B59B6' } },
      { scope: ['markup.inserted'], settings: { foreground: '#2ECC71', fontStyle: 'bold' } },
    ]
  }
];

function generateThemes() {
  const outputDir = path.join(__dirname, '../../extensions/vscode/themes');
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  for (const theme of themes) {
    const themeJson = {
      name: theme.name,
      type: theme.type,
      colors: theme.colors,
      tokenColors: theme.tokenColors
    };

    const fileName = theme.name.toLowerCase().replace(/\s+/g, '-') + '-color-theme.json';
    fs.writeFileSync(path.join(outputDir, fileName), JSON.stringify(themeJson, null, 2));
    console.log(`  ✅ Generated: ${fileName}`);
  }

  console.log(`\n🎉 Generated ${themes.length} themes!`);
}

generateThemes();
